CREATE TABLE IF NOT EXISTS place (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
slug VARCHAR(255) NOT NULL,
STATE VARCHAR(255) NOT NULL,
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP NOT NULL
);